name: Generate PDF Resume

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: mkdir
        run: mkdir resumes

      - name: Build
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Wait for Server
        run: sleep 10

      - name: Generate PDF
        run: npm run pdf

      - name: Copy to s3
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          source: './resumes'
          dest: s3://${{ secrets.BUCKET_NAME }}/static/resume
          flags: --recursive --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers